version: 2
updates:
  - package-ecosystem: 'npm' # Tipo de paquete, por ejemplo npm, maven, pip, etc.
    directory: '/' # La ubicación del archivo de configuración del paquete.
    schedule:
      interval: 'daily' # La frecuencia con que Dependabot buscará actualizaciones.
